//! The desktop shell.
//!
//! There is deliberately almost nothing here. Every command is one line that
//! hands its arguments to [`notetaker_core::dispatch`], which is the same entry
//! point the HTTP server uses — so the thirty-arm match that decides what a
//! command *means* is written once, tested on Linux, and cannot drift between
//! the desktop app and the served UI.
//!
//! The three exceptions are `set_tray_status`, `list_input_devices`, and
//! `permission_status` under "the shell itself": they describe this window or
//! this machine, which a phone on the LAN does not have, so they belong to the
//! shell and not to the contract.
//!
//! **This crate cannot be compiled on the development machine** (webkit/gtk and
//! `libdbus-sys` need system packages there is no sudo to install), so CI is the
//! only thing that ever type-checks it. That is why the wrappers are written out
//! longhand rather than generated by a macro: boring, repetitive code a reader
//! can check by eye is the right trade when the compiler is not available to the
//! author. Each uses only `#[tauri::command]` with named parameters and `State`,
//! which is the most stable corner of the Tauri API.
//!
//! `rename_all = "camelCase"` is on every command with a multi-word argument.
//! `src/lib/ipc.ts` sends `summaryMd`, `notesMd`, `appId`; the Rust parameters
//! are `summary_md`, `notes_md`, `app_id`. A mismatch is not a compile error and
//! not a visible crash — the invoke simply rejects at runtime and the user reads
//! it as "the button does nothing". `runtime::COMMANDS` is the written-down
//! contract, and a test fails the build if either side drifts from it.

mod tray;
mod windowing;

use std::path::Path;
use notetaker_core::capture::platform::PlatformSources;
use notetaker_core::dispatch::dispatch;
use notetaker_core::logging;
use notetaker_core::paths;
use notetaker_core::power::probe::default_probe;
use notetaker_core::runtime::Runtime;
use serde_json::{json, Value};
use tauri::{Emitter, Manager, State};

/// Runs one command through core's dispatcher.
///
/// Errors come back as `String` because that is what Tauri sends to the UI. The
/// runtime already writes its failures for someone who is not an engineer, so
/// the message passes through unchanged — `{:#}` keeps the `anyhow` context
/// chain, which is where the useful half of these messages lives.
fn call(rt: &State<'_, Runtime>, command: &str, args: Value) -> Result<Value, String> {
    dispatch(rt.inner(), command, &args).map_err(|e| format!("{e:#}"))
}

// --- library ---------------------------------------------------------------

#[tauri::command]
fn list_tasks(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_tasks", json!({}))
}

#[tauri::command]
fn create_task(rt: State<'_, Runtime>, name: String) -> Result<Value, String> {
    call(&rt, "create_task", json!({ "name": name }))
}

#[tauri::command]
fn list_recordings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_recordings", json!({}))
}

#[tauri::command]
fn list_archived_recordings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_archived_recordings", json!({}))
}

#[tauri::command]
fn get_recording(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "get_recording", json!({ "id": id }))
}

#[tauri::command]
fn search(rt: State<'_, Runtime>, query: String) -> Result<Value, String> {
    call(&rt, "search", json!({ "query": query }))
}

#[tauri::command]
fn process_now(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "process_now", json!({ "id": id }))
}

#[tauri::command(rename_all = "camelCase")]
fn update_summary(rt: State<'_, Runtime>, id: String, summary_md: String) -> Result<Value, String> {
    call(
        &rt,
        "update_summary",
        json!({ "id": id, "summaryMd": summary_md }),
    )
}

#[tauri::command]
fn assign_task(rt: State<'_, Runtime>, id: String, task: String) -> Result<Value, String> {
    call(&rt, "assign_task", json!({ "id": id, "task": task }))
}

#[tauri::command]
fn rename_recording(rt: State<'_, Runtime>, id: String, title: String) -> Result<Value, String> {
    call(&rt, "rename_recording", json!({ "id": id, "title": title }))
}

#[tauri::command]
fn archive_recording(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "archive_recording", json!({ "id": id }))
}

#[tauri::command]
fn restore_recording(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "restore_recording", json!({ "id": id }))
}

#[tauri::command]
fn delete_recording(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "delete_recording", json!({ "id": id }))
}

#[tauri::command]
fn rename_speaker(
    rt: State<'_, Runtime>,
    id: String,
    key: String,
    name: String,
) -> Result<Value, String> {
    call(
        &rt,
        "rename_speaker",
        json!({ "id": id, "key": key, "name": name }),
    )
}

// --- the notepad -----------------------------------------------------------

#[tauri::command(rename_all = "camelCase")]
fn save_notes(rt: State<'_, Runtime>, id: String, notes_md: String) -> Result<Value, String> {
    call(&rt, "save_notes", json!({ "id": id, "notesMd": notes_md }))
}

#[tauri::command]
fn append_note(rt: State<'_, Runtime>, id: String, jot: String) -> Result<Value, String> {
    call(&rt, "append_note", json!({ "id": id, "jot": jot }))
}

#[tauri::command]
fn add_highlight(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "add_highlight", json!({}))
}

#[tauri::command]
fn list_templates(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_templates", json!({}))
}

#[tauri::command]
fn set_template(rt: State<'_, Runtime>, id: String, template: String) -> Result<Value, String> {
    call(
        &rt,
        "set_template",
        json!({ "id": id, "template": template }),
    )
}

#[tauri::command]
fn set_action_done(
    rt: State<'_, Runtime>,
    id: String,
    index: usize,
    done: bool,
) -> Result<Value, String> {
    call(
        &rt,
        "set_action_done",
        json!({ "id": id, "index": index, "done": done }),
    )
}

#[tauri::command]
fn ask_recording(rt: State<'_, Runtime>, id: String, question: String) -> Result<Value, String> {
    call(
        &rt,
        "ask_recording",
        json!({ "id": id, "question": question }),
    )
}

#[tauri::command]
fn start_live_ask(
    rt: State<'_, Runtime>,
    question: String,
    context: String,
) -> Result<Value, String> {
    call(
        &rt,
        "start_live_ask",
        json!({ "question": question, "context": context }),
    )
}

#[tauri::command]
fn poll_live_ask(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "poll_live_ask", json!({ "id": id }))
}

#[tauri::command]
fn audio_path(rt: State<'_, Runtime>, id: String, track: String) -> Result<Value, String> {
    call(&rt, "audio_path", json!({ "id": id, "track": track }))
}

#[tauri::command]
fn log_path(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "log_path", json!({}))
}

// --- settings --------------------------------------------------------------

#[tauri::command]
fn get_settings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "get_settings", json!({}))
}

/// Takes the settings blob as an opaque `Value` on purpose: the shape is
/// `api::Settings`, and re-declaring it here would be a second definition of the
/// same contract that could drift from the first. `dispatch` deserializes it.
#[tauri::command]
fn set_settings(rt: State<'_, Runtime>, settings: Value) -> Result<Value, String> {
    call(&rt, "set_settings", json!({ "settings": settings }))
}

#[tauri::command(rename_all = "camelCase")]
fn set_auto_record(
    rt: State<'_, Runtime>,
    app_id: String,
    policy: String,
) -> Result<Value, String> {
    call(
        &rt,
        "set_auto_record",
        json!({ "appId": app_id, "policy": policy }),
    )
}

// --- capture ---------------------------------------------------------------

#[tauri::command]
fn start_capture(rt: State<'_, Runtime>, mode: String, title: String) -> Result<Value, String> {
    call(
        &rt,
        "start_capture",
        json!({ "mode": mode, "title": title }),
    )
}

#[tauri::command]
fn pause_capture(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "pause_capture", json!({}))
}

#[tauri::command]
fn resume_capture(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "resume_capture", json!({}))
}

#[tauri::command]
fn stop_capture(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "stop_capture", json!({}))
}

#[tauri::command]
fn capture_status(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "capture_status", json!({}))
}

#[tauri::command]
fn capture_levels(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "capture_levels", json!({}))
}

#[tauri::command]
fn live_transcript(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "live_transcript", json!({}))
}

#[tauri::command]
fn live_transcript_stats(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "live_transcript_stats", json!({}))
}

#[tauri::command]
fn start_dictation(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "start_dictation", json!({}))
}

#[tauri::command]
fn stop_dictation(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "stop_dictation", json!({}))
}

#[tauri::command]
fn cancel_dictation(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "cancel_dictation", json!({}))
}

#[tauri::command]
fn dictation_status(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "dictation_status", json!({}))
}

#[tauri::command]
fn copy_last_transcript(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "copy_last_transcript", json!({}))
}

#[tauri::command]
fn poll_meetings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "poll_meetings", json!({}))
}

// --- models and setup ------------------------------------------------------

#[tauri::command]
fn ollama_status(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "ollama_status", json!({}))
}

#[tauri::command]
fn pull_model(rt: State<'_, Runtime>, model: String) -> Result<Value, String> {
    call(&rt, "pull_model", json!({ "model": model }))
}

#[tauri::command]
fn pull_progress(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "pull_progress", json!({}))
}

#[tauri::command]
fn download_models(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "download_models", json!({}))
}

#[tauri::command]
fn adopt_models(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "adopt_models", json!({}))
}

#[tauri::command]
fn find_existing_models(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "find_existing_models", json!({}))
}

#[tauri::command]
fn detected_tier(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "detected_tier", json!({}))
}

#[tauri::command]
fn setup_status(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "setup_status", json!({}))
}

// --- the shell itself ------------------------------------------------------
//
// The only two commands that do not go through `dispatch`, because they are
// about *this window and this machine* rather than about the library: a tray
// that the served UI does not have, and the microphones plugged into the
// computer the app is installed on. They are deliberately absent from
// `runtime::COMMANDS` — a phone on the LAN has neither — and `src/lib/desktop.ts`
// is the only caller, which checks `isDesktop()` before every one of them.

#[tauri::command]
fn set_tray_status(app: tauri::AppHandle, state: String, status_line: String) {
    tray::set_state(&app, &state, &status_line);
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct InputDevice {
    id: String,
    label: String,
    is_default: bool,
}

#[tauri::command]
fn list_input_devices() -> Vec<InputDevice> {
    use cpal::traits::{DeviceTrait, HostTrait};
    let host = cpal::default_host();
    let default_name = host
        .default_input_device()
        .and_then(|d| d.name().ok())
        .unwrap_or_default();
    host.input_devices()
        .map(|devices| {
            devices
                .filter_map(|d| d.name().ok())
                .map(|name| InputDevice {
                    id: name.clone(),
                    label: name.clone(),
                    is_default: name == default_name,
                })
                .collect()
        })
        .unwrap_or_default()
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct PermissionStatus {
    microphone: bool,
    accessibility: bool,
    input_monitoring: bool,
    input_monitoring_required: bool,
}

/// Reads the local machine's permission state without prompting. The frontend
/// polls this after the user returns from System Settings; a stale grant is
/// indistinguishable from a broken paste path if it is read only at startup.
#[tauri::command]
fn permission_status() -> PermissionStatus {
    let status = notetaker_platform::permission_status();
    PermissionStatus {
        microphone: status.microphone,
        accessibility: status.accessibility,
        input_monitoring: status.input_monitoring,
        input_monitoring_required: status.input_monitoring_required,
    }
}

/// Builds the runtime the whole app hangs off.
///
/// Identical to what `notetaker-serve` does, deliberately: two transports over
/// one runtime, constructed the same way, so a bug cannot be present in one and
/// absent in the other.
fn open_runtime(app_dir: &Path) -> anyhow::Result<Runtime> {
    let storage_root = paths::default_storage_root()?;
    log::info!("library: {}", storage_root.display());

    Runtime::open(
        app_dir,
        &storage_root,
        Box::new(PlatformSources::new()),
        default_probe(),
    )
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        // First, deliberately. Plugins initialise in the order they are added
        // (tauri-plugin-single-instance's own README says so), so a second
        // launch has to hit this one before anything else has a chance to open
        // a log file, claim the tray, or start a runtime it will never use.
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            if let Some(win) = app.get_webview_window("main") {
                let _ = win.show();
                let _ = win.unminimize();
                let _ = win.set_focus();
            }
        }))
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_dialog::init());

    // tauri-nspanel is AppKit-backed and cannot even compile for Windows.
    // The windowing module keeps the matching panel behavior behind this same
    // platform boundary, while Windows uses ordinary Tauri windows.
    #[cfg(target_os = "macos")]
    let builder = builder.plugin(tauri_nspanel::init());

    #[cfg(not(target_os = "macos"))]
    let builder = builder;

    builder
        // DECORATIONS excluded: whether a window has OS chrome is the
        // platform's decision, made in config — native overlay titlebar on
        // macOS, our own drawn one on Windows — not user state to remember.
        // Left in, a `.window-state.json` written by an older build restores
        // its stale `decorated: false` over the config on every launch, which
        // is exactly how the macOS traffic lights failed to appear.
        .plugin(
            tauri_plugin_window_state::Builder::default()
                .with_state_flags(
                    tauri_plugin_window_state::StateFlags::all()
                        & !tauri_plugin_window_state::StateFlags::DECORATIONS,
                )
                .build(),
        )
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .setup(|app| {
            let app_dir = app.path().app_data_dir()?;
            logging::install(&app_dir);
            let runtime = open_runtime(&app_dir)?;
            // Recovers what a crash left behind, rebuilds the search index, and
            // starts transcribing in the background. One call, shared with
            // `notetaker-serve`, because this crate never compiles on the
            // development machine — anything written here and nowhere else is
            // unverified until CI.
            runtime.launch();

            app.manage(runtime);

            // After `manage`, because the tray's own state goes into the same
            // store. The returned handle is dropped on purpose: Tauri keeps the
            // icon in its resource table, and `tray_by_id` is how it is reached
            // again.
            tray::build(&app.handle().clone())?;

            // The floating overlay: a small always-on-top pill the main
            // webview shows and hides (its visibility policy lives in
            // settings, which the main webview already watches). Created here
            // rather than in config so the macOS overlay file doesn't have to
            // mirror the whole windows array. Hidden until wanted.
            //
            // `content_protected` keeps it out of screen shares — a recording
            // indicator the other side of the call can see is a worse
            // presence than a bot. `visible_on_all_workspaces` because a
            // meeting is usually fullscreen on its own space, which is
            // exactly where the pill must follow.
            {
                let overlay = tauri::WebviewWindowBuilder::new(
                    app,
                    "overlay",
                    tauri::WebviewUrl::App("index.html#overlay".into()),
                )
                .title("Notetaker overlay")
                .inner_size(300.0, 48.0)
                .resizable(false)
                .maximizable(false)
                .minimizable(false)
                .decorations(false)
                .transparent(true)
                .always_on_top(true)
                .visible_on_all_workspaces(true)
                .content_protected(true)
                .skip_taskbar(true)
                .visible(false)
                .build()?;
                windowing::configure_overlay_panel(&overlay)?;
                windowing::apply_vibrancy(&overlay);
                // Top-right of the primary screen, clear of the menu bar and
                // the notch, mirroring where every OS puts its own overlays.
                if let Ok(Some(monitor)) = overlay.primary_monitor() {
                    let size = monitor.size();
                    let scale = monitor.scale_factor();
                    let x = (size.width as f64 / scale) - 300.0 - 16.0;
                    let _ = overlay.set_position(tauri::LogicalPosition::new(x, 48.0));
                }
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            list_tasks,
            create_task,
            list_recordings,
            list_archived_recordings,
            get_recording,
            search,
            process_now,
            update_summary,
            assign_task,
            rename_recording,
            archive_recording,
            restore_recording,
            delete_recording,
            rename_speaker,
            save_notes,
            append_note,
            add_highlight,
            list_templates,
            set_template,
            set_action_done,
            ask_recording,
            start_live_ask,
            poll_live_ask,
            audio_path,
            log_path,
            get_settings,
            set_settings,
            set_auto_record,
            start_capture,
            pause_capture,
            resume_capture,
            stop_capture,
            capture_status,
            capture_levels,
            live_transcript,
            live_transcript_stats,
            start_dictation,
            stop_dictation,
            cancel_dictation,
            dictation_status,
            copy_last_transcript,
            poll_meetings,
            ollama_status,
            pull_model,
            pull_progress,
            download_models,
            adopt_models,
            find_existing_models,
            detected_tier,
            setup_status,
            set_tray_status,
            list_input_devices,
            permission_status,
        ])
        .on_window_event(|window, event| {
            // The overlay is persistent while recording. Closing it means
            // hide, never destroy; the main owner will show it again on the
            // next sync if the setting still allows it.
            if window.label() == "overlay" {
                if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                    api.prevent_close();
                    let _ = window.hide();
                }
                return;
            }

            if window.label() != "main" {
                return;
            }
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                // The frontend owns the decision (setting + first-time note).
                api.prevent_close();
                let _ = window.emit("close-requested", ());
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
