//! The desktop shell.
//!
//! There is deliberately almost nothing here. Every command is one line that
//! hands its arguments to [`notetaker_core::dispatch`], which is the same entry
//! point the HTTP server uses — so the thirty-arm match that decides what a
//! command *means* is written once, tested on Linux, and cannot drift between
//! the desktop app and the served UI.
//!
//! **This crate cannot be compiled on the development machine** (webkit/gtk and
//! `libdbus-sys` need system packages there is no sudo to install), so CI is the
//! only thing that ever type-checks it. That is why the wrappers are written out
//! longhand rather than generated by a macro: boring, repetitive code a reader
//! can check by eye is the right trade when the compiler is not available to the
//! author. Each uses only `#[tauri::command]` with named parameters and `State`,
//! which is the most stable corner of the Tauri API.
//!
//! `rename_all = "camelCase"` is on every command with a multi-word argument.
//! `src/lib/ipc.ts` sends `summaryMd`, `notesMd`, `appId`; the Rust parameters
//! are `summary_md`, `notes_md`, `app_id`. A mismatch is not a compile error and
//! not a visible crash — the invoke simply rejects at runtime and the user reads
//! it as "the button does nothing". `runtime::COMMANDS` is the written-down
//! contract, and a test fails the build if either side drifts from it.

use notetaker_core::capture::platform::PlatformSources;
use notetaker_core::dispatch::dispatch;
use notetaker_core::paths;
use notetaker_core::power::probe::default_probe;
use notetaker_core::runtime::Runtime;
use serde_json::{json, Value};
use tauri::{Manager, State};

/// Runs one command through core's dispatcher.
///
/// Errors come back as `String` because that is what Tauri sends to the UI. The
/// runtime already writes its failures for someone who is not an engineer, so
/// the message passes through unchanged — `{:#}` keeps the `anyhow` context
/// chain, which is where the useful half of these messages lives.
fn call(rt: &State<'_, Runtime>, command: &str, args: Value) -> Result<Value, String> {
    dispatch(rt.inner(), command, &args).map_err(|e| format!("{e:#}"))
}

// --- library ---------------------------------------------------------------

#[tauri::command]
fn list_tasks(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_tasks", json!({}))
}

#[tauri::command]
fn create_task(rt: State<'_, Runtime>, name: String) -> Result<Value, String> {
    call(&rt, "create_task", json!({ "name": name }))
}

#[tauri::command]
fn list_recordings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_recordings", json!({}))
}

#[tauri::command]
fn get_recording(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "get_recording", json!({ "id": id }))
}

#[tauri::command]
fn search(rt: State<'_, Runtime>, query: String) -> Result<Value, String> {
    call(&rt, "search", json!({ "query": query }))
}

#[tauri::command]
fn process_now(rt: State<'_, Runtime>, id: String) -> Result<Value, String> {
    call(&rt, "process_now", json!({ "id": id }))
}

#[tauri::command(rename_all = "camelCase")]
fn update_summary(rt: State<'_, Runtime>, id: String, summary_md: String) -> Result<Value, String> {
    call(
        &rt,
        "update_summary",
        json!({ "id": id, "summaryMd": summary_md }),
    )
}

#[tauri::command]
fn assign_task(rt: State<'_, Runtime>, id: String, task: String) -> Result<Value, String> {
    call(&rt, "assign_task", json!({ "id": id, "task": task }))
}

#[tauri::command]
fn rename_recording(rt: State<'_, Runtime>, id: String, title: String) -> Result<Value, String> {
    call(&rt, "rename_recording", json!({ "id": id, "title": title }))
}

#[tauri::command]
fn rename_speaker(
    rt: State<'_, Runtime>,
    id: String,
    key: String,
    name: String,
) -> Result<Value, String> {
    call(
        &rt,
        "rename_speaker",
        json!({ "id": id, "key": key, "name": name }),
    )
}

// --- the notepad -----------------------------------------------------------

#[tauri::command(rename_all = "camelCase")]
fn save_notes(rt: State<'_, Runtime>, id: String, notes_md: String) -> Result<Value, String> {
    call(&rt, "save_notes", json!({ "id": id, "notesMd": notes_md }))
}

#[tauri::command]
fn list_templates(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "list_templates", json!({}))
}

#[tauri::command]
fn set_template(rt: State<'_, Runtime>, id: String, template: String) -> Result<Value, String> {
    call(
        &rt,
        "set_template",
        json!({ "id": id, "template": template }),
    )
}

#[tauri::command]
fn set_action_done(
    rt: State<'_, Runtime>,
    id: String,
    index: usize,
    done: bool,
) -> Result<Value, String> {
    call(
        &rt,
        "set_action_done",
        json!({ "id": id, "index": index, "done": done }),
    )
}

#[tauri::command]
fn ask_recording(rt: State<'_, Runtime>, id: String, question: String) -> Result<Value, String> {
    call(
        &rt,
        "ask_recording",
        json!({ "id": id, "question": question }),
    )
}

#[tauri::command]
fn audio_path(rt: State<'_, Runtime>, id: String, track: String) -> Result<Value, String> {
    call(&rt, "audio_path", json!({ "id": id, "track": track }))
}

// --- settings --------------------------------------------------------------

#[tauri::command]
fn get_settings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "get_settings", json!({}))
}

/// Takes the settings blob as an opaque `Value` on purpose: the shape is
/// `api::Settings`, and re-declaring it here would be a second definition of the
/// same contract that could drift from the first. `dispatch` deserializes it.
#[tauri::command]
fn set_settings(rt: State<'_, Runtime>, settings: Value) -> Result<Value, String> {
    call(&rt, "set_settings", json!({ "settings": settings }))
}

#[tauri::command(rename_all = "camelCase")]
fn set_auto_record(
    rt: State<'_, Runtime>,
    app_id: String,
    policy: String,
) -> Result<Value, String> {
    call(
        &rt,
        "set_auto_record",
        json!({ "appId": app_id, "policy": policy }),
    )
}

// --- capture ---------------------------------------------------------------

#[tauri::command]
fn start_capture(rt: State<'_, Runtime>, mode: String, title: String) -> Result<Value, String> {
    call(
        &rt,
        "start_capture",
        json!({ "mode": mode, "title": title }),
    )
}

#[tauri::command]
fn pause_capture(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "pause_capture", json!({}))
}

#[tauri::command]
fn resume_capture(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "resume_capture", json!({}))
}

#[tauri::command]
fn stop_capture(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "stop_capture", json!({}))
}

#[tauri::command]
fn capture_status(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "capture_status", json!({}))
}

#[tauri::command]
fn poll_meetings(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "poll_meetings", json!({}))
}

// --- models and setup ------------------------------------------------------

#[tauri::command]
fn ollama_status(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "ollama_status", json!({}))
}

#[tauri::command]
fn pull_model(rt: State<'_, Runtime>, model: String) -> Result<Value, String> {
    call(&rt, "pull_model", json!({ "model": model }))
}

#[tauri::command]
fn pull_progress(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "pull_progress", json!({}))
}

#[tauri::command]
fn download_models(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "download_models", json!({}))
}

#[tauri::command]
fn detected_tier(rt: State<'_, Runtime>) -> Result<Value, String> {
    call(&rt, "detected_tier", json!({}))
}

/// Builds the runtime the whole app hangs off.
///
/// Identical to what `notetaker-serve` does, deliberately: two transports over
/// one runtime, constructed the same way, so a bug cannot be present in one and
/// absent in the other.
fn open_runtime() -> anyhow::Result<Runtime> {
    let storage_root = paths::default_storage_root()?;
    let app_dir = paths::default_app_dir()?;
    log::info!("library: {}", storage_root.display());

    Runtime::open(
        &app_dir,
        &storage_root,
        Box::new(PlatformSources::new()),
        default_probe(),
    )
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let runtime = open_runtime()?;

            // Recovers what a crash left behind, rebuilds the search index, and
            // starts transcribing in the background. One call, shared with
            // `notetaker-serve`, because this crate never compiles on the
            // development machine — anything written here and nowhere else is
            // unverified until CI.
            runtime.launch();

            app.manage(runtime);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            list_tasks,
            create_task,
            list_recordings,
            get_recording,
            search,
            process_now,
            update_summary,
            assign_task,
            rename_recording,
            rename_speaker,
            save_notes,
            list_templates,
            set_template,
            set_action_done,
            ask_recording,
            audio_path,
            get_settings,
            set_settings,
            set_auto_record,
            start_capture,
            pause_capture,
            resume_capture,
            stop_capture,
            capture_status,
            poll_meetings,
            ollama_status,
            pull_model,
            pull_progress,
            download_models,
            detected_tier,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
